#!/usr/bin/env python3
"""
Live2D Master Agent - PSD Parser with Malicious File Protection (P2-1 FIXED)

P2-1: Before parsing any PSD file, validates:
- File magic bytes
- File size limits
- Dimension limits
- Channel count limits
- Layer count limits (prevents zip bombs)

Uses psd-tools when available; provides a lightweight built-in header parser
for validation even without psd-tools installed.
"""

import os
import struct
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any

from core.logger import get_logger
from core.security import (
    validate_psd_file, scan_psd_layer_count,
    MAX_PSD_SIZE_BYTES, MAX_PSD_LAYERS, MAX_PSD_DIMENSION, MAX_PSD_CHANNELS,
)

log = get_logger("psd_parser")


class PSDValidationError(Exception):
    """Raised when a PSD file fails security validation."""
    pass


class PSDParser:
    """Safe PSD parser with malicious file protection (P2-1).

    P2-2: QA issue IDs generated by this parser are STABLE (hashed)
    so they don't change between runs on the same file.
    """

    def __init__(self, max_size_mb: int = 500, max_layers: int = 2000):
        self.max_size_mb = max_size_mb
        self.max_layers = max_layers

    def parse(self, filepath: str) -> Dict[str, Any]:
        """Parse a PSD file safely.

        Returns metadata dict with keys:
        - valid: bool
        - width, height, channels, depth, color_mode
        - layer_count
        - layers: list of dicts with name, rect, visible
        - error: error message if invalid

        Raises PSDValidationError if file is malicious/corrupt.
        """
        filepath = str(Path(filepath).resolve())

        # P2-1: Security validation BEFORE any parsing
        valid, reason = validate_psd_file(filepath, max_size_mb=self.max_size_mb)
        if not valid:
            raise PSDValidationError(f"PSD validation failed: {reason}")

        safe, layer_count = scan_psd_layer_count(filepath, max_layers=self.max_layers)
        if not safe:
            raise PSDValidationError(
                f"PSD has too many layers ({layer_count} > {self.max_layers}). "
                "This may be a malicious file."
            )

        # Parse using psd-tools if available
        try:
            return self._parse_with_psd_tools(filepath)
        except ImportError:
            return self._parse_header_only(filepath)

    def _parse_with_psd_tools(self, filepath: str) -> Dict[str, Any]:
        """Parse using psd-tools library."""
        from psd_tools import PSDImage

        psd = PSDImage.open(filepath)

        layers_info = []
        for i, layer in enumerate(psd.descendants()):
            # P2-2: Stable issue ID using layer name hash + position
            stable_id = self._make_stable_layer_id(layer.name or f"layer_{i}", i, layer.offset, layer.size)
            layers_info.append({
                "index": i,
                "stable_id": stable_id,
                "name": layer.name or f"Layer {i}",
                "visible": layer.visible,
                "offset": (layer.offset[0] if hasattr(layer, 'offset') else 0,
                          layer.offset[1] if hasattr(layer, 'offset') else 0),
                "size": (layer.size[0] if hasattr(layer, 'size') else psd.width,
                        layer.size[1] if hasattr(layer, 'size') else psd.height),
                "kind": str(layer.kind) if hasattr(layer, 'kind') else "unknown",
                "opacity": getattr(layer, 'opacity', 255),
            })

        return {
            "valid": True,
            "filepath": filepath,
            "width": psd.width,
            "height": psd.height,
            "channels": getattr(psd, 'channels', 4),
            "depth": getattr(psd, 'depth', 8),
            "color_mode": str(getattr(psd, 'color_mode', 'RGB')),
            "layer_count": len(layers_info),
            "layers": layers_info,
        }

    def _parse_header_only(self, filepath: str) -> Dict[str, Any]:
        """Lightweight header parser when psd-tools is not available."""
        with open(filepath, 'rb') as f:
            magic = f.read(4)
            version = struct.unpack('>H', f.read(2))[0]
            f.read(6)  # reserved
            channels = struct.unpack('>H', f.read(2))[0]
            height = struct.unpack('>I', f.read(4))[0]
            width = struct.unpack('>I', f.read(4))[0]
            depth = struct.unpack('>H', f.read(2))[0]
            color_mode = struct.unpack('>H', f.read(2))[0]

        color_mode_names = {0: "Bitmap", 1: "Grayscale", 2: "Indexed", 3: "RGB",
                           4: "CMYK", 7: "Multichannel", 8: "Duotone", 9: "Lab"}

        return {
            "valid": True,
            "filepath": filepath,
            "width": width,
            "height": height,
            "channels": channels,
            "depth": depth,
            "color_mode": color_mode_names.get(color_mode, f"Unknown({color_mode})"),
            "layer_count": None,  # Can't count without psd-tools
            "layers": [],
            "note": "Header only - install psd-tools for full layer parsing",
        }

    def _make_stable_layer_id(self, name: str, index: int, offset: tuple, size: tuple) -> str:
        """P2-2 FIX: Generate a stable issue ID for a layer.

        Uses hash of name + position so the same layer gets the same ID
        across multiple runs on the same file.
        """
        import hashlib
        ox, oy = (offset or (0, 0))
        sw, sh = (size or (0, 0))
        key = f"{name}|{ox},{oy}|{sw}x{sh}"
        h = hashlib.sha256(key.encode('utf-8')).hexdigest()[:12]
        return f"LAYER-{h}"


def validate_and_parse_psd(filepath: str) -> Dict[str, Any]:
    """Convenience function: safely parse a PSD file."""
    parser = PSDParser()
    return parser.parse(filepath)
