#!/usr/bin/env python3
"""
__PET_NAME__ - AI Desktop Pet
Generated by AI Pet Generator

Controls:
  Left-click pet   -> Happy expression
  Right-click      -> Random expression
  Drag pet         -> Move to position
  ESC              -> Exit
"""

import os
import sys
import math
import random
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
LAYERS_DIR = os.path.join(SCRIPT_DIR, "layers")
CONFIG_PATH = os.path.join(SCRIPT_DIR, "pet_config.json")
os.chdir(SCRIPT_DIR)

import json
import pygame

def load_config():
    try:
        with open(CONFIG_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {
            "name": "__PET_NAME__",
            "canvas_size": [256, 384],
            "fps": 60,
            "layer_groups": {},
            "animations": {
                "body_swing_amplitude": 3.0,
                "body_swing_speed": 0.8,
                "breath_amplitude": 1.5,
                "breath_speed": 0.4,
                "blink_interval_min": 3.0,
                "blink_interval_max": 6.0,
                "blink_duration": 0.15,
                "hair_swing_multiplier": 1.8,
                "expression_change_interval": 10.0,
                "expression_transition_time": 0.3,
            },
            "expressions": {
                "normal": {
                    "mouth_scale_y": 1.0, "mouth_scale_x": 1.0,
                    "eye_open": 1.0, "eye_scale_x": 1.0,
                    "eyebrow_angle": 0.0, "eyebrow_offset_y": 0.0,
                    "blush": False, "blush_intensity": 0.0,
                    "face_offset_y": 0.0, "face_offset_x": 0.0,
                },
                "happy": {
                    "mouth_scale_y": 1.15, "mouth_scale_x": 1.1,
                    "eye_open": 0.7, "eye_scale_x": 0.9,
                    "eyebrow_angle": -0.15, "eyebrow_offset_y": 3.0,
                    "blush": True, "blush_intensity": 0.6,
                    "face_offset_y": 2.0, "face_offset_x": 0.0,
                },
                "shy": {
                    "mouth_scale_y": 0.85, "mouth_scale_x": 0.9,
                    "eye_open": 0.5, "eye_scale_x": 0.8,
                    "eyebrow_angle": -0.2, "eyebrow_offset_y": 2.0,
                    "blush": True, "blush_intensity": 0.8,
                    "face_offset_y": -1.0, "face_offset_x": 0.0,
                },
                "surprised": {
                    "mouth_scale_y": 1.3, "mouth_scale_x": 1.15,
                    "eye_open": 1.2, "eye_scale_x": 1.1,
                    "eyebrow_angle": 0.2, "eyebrow_offset_y": 5.0,
                    "blush": False, "blush_intensity": 0.0,
                    "face_offset_y": 3.0, "face_offset_x": 0.0,
                },
                "sleepy": {
                    "mouth_scale_y": 0.7, "mouth_scale_x": 1.0,
                    "eye_open": 0.25, "eye_scale_x": 1.0,
                    "eyebrow_angle": 0.1, "eyebrow_offset_y": -2.0,
                    "blush": False, "blush_intensity": 0.0,
                    "face_offset_y": -2.0, "face_offset_x": 0.0,
                },
                "angry": {
                    "mouth_scale_y": 0.7, "mouth_scale_x": 0.85,
                    "eye_open": 0.9, "eye_scale_x": 1.1,
                    "eyebrow_angle": 0.3, "eyebrow_offset_y": -3.0,
                    "blush": True, "blush_intensity": 0.4,
                    "face_offset_y": -1.0, "face_offset_x": 0.0,
                },
                "sad": {
                    "mouth_scale_y": 0.9, "mouth_scale_x": 0.85,
                    "eye_open": 0.8, "eye_scale_x": 0.95,
                    "eyebrow_angle": -0.1, "eyebrow_offset_y": -2.0,
                    "blush": False, "blush_intensity": 0.0,
                    "face_offset_y": -3.0, "face_offset_x": 0.0,
                },
            },
        }

def load_layers(layers_dir):
    layers = []
    if not os.path.isdir(layers_dir):
        return [create_default_pet_layer()]
    for fname in sorted(os.listdir(layers_dir)):
        if fname.endswith(".png"):
            path = os.path.join(layers_dir, fname)
            try:
                surf = pygame.image.load(path).convert_alpha()
                layers.append((fname, surf))
            except Exception:
                pass
    return layers if layers else [create_default_pet_layer()]

def get_layer_group(fname, layer_groups):
    name_no_ext = os.path.splitext(fname)[0].lower()
    for group, names in layer_groups.items():
        for n in names:
            if n.lower() == name_no_ext or n.lower() in name_no_ext:
                return group
    keywords = {
        "hair_front": ["hair", "bangs", "ahoge", "sidehair", "头发"],
        "hair_back": ["hair_back", "头发_back"],
        "eyes": ["eye", "iris", "pupil", "highlight", "眼睛"],
        "mouth": ["mouth", "lip", "teeth", "tongue", "嘴巴"],
        "eyebrows": ["eyebrow", "brow", "眉毛"],
        "face": ["face", "skin", "nose", "ear", "blush", "脸", "皮肤"],
        "body_swing": ["body", "chest", "clothes", "torso", "waist", "衣服", "身体"],
        "body_static": ["body_static", "shadow", "阴影", "background"],
    }
    for group, kws in keywords.items():
        for kw in kws:
            if kw in name_no_ext:
                return group
    return "body_static"

def create_default_pet_layer():
    surf = pygame.Surface((128, 128), pygame.SRCALPHA)
    pygame.draw.circle(surf, (255, 200, 200), (64, 64), 50)
    pygame.draw.circle(surf, (100, 100, 200), (48, 54), 8)
    pygame.draw.circle(surf, (100, 100, 200), (80, 54), 8)
    pygame.draw.circle(surf, (255, 150, 150), (64, 75), 12, 2)
    return ("default", surf)

def clamp(val, low, high):
    return max(low, min(high, val))

def lerp(a, b, t):
    return a + (b - a) * t

def create_blush_surface(radius, intensity, base_color=(255, 180, 180)):
    """Pre-render a blush surface for efficient blitting.
    
    Creates a circular gradient blush that can be reused each frame.
    """
    size = radius * 2 + 2
    surf = pygame.Surface((size, size), pygame.SRCALPHA)
    center = radius + 1
    
    for y in range(size):
        for x in range(size):
            dist = math.sqrt((x - center) ** 2 + (y - center) ** 2)
            if dist <= radius:
                falloff = 1 - (dist / radius)
                alpha = int(255 * intensity * falloff * falloff * 0.7)
                r = min(255, base_color[0])
                g = min(255, base_color[1])
                b = min(255, base_color[2])
                surf.set_at((x, y), (r, g, b, alpha))
    
    return surf

def draw_blush(screen, center_x, center_y, intensity, w, h):
    """Draw blush circles on cheeks using pre-rendered surfaces.
    
    Uses efficient surface creation instead of per-pixel set_at.
    """
    if intensity <= 0:
        return
    
    blush_radius = int(w * 0.12)
    blush_offset = int(w * 0.15)
    
    left_x = int(center_x - blush_offset)
    right_x = int(center_x + blush_offset)
    cheek_y = int(center_y + h * 0.1)
    
    blush_surf = create_blush_surface(blush_radius, intensity)
    bw, bh = blush_surf.get_size()
    
    screen.blit(blush_surf, (left_x - bw // 2, cheek_y - bh // 2))
    screen.blit(blush_surf, (right_x - bw // 2, cheek_y - bh // 2))

def main():
    pygame.init()
    config = load_config()
    w, h = config.get("canvas_size", [256, 384])
    fps = config.get("fps", 60)
    anim = config.get("animations", {})
    expressions = config.get("expressions", {})
    layer_groups = config.get("layer_groups", {})

    screen = pygame.display.set_mode((w, h), pygame.NOFRAME | pygame.SRCALPHA)
    pygame.display.set_caption(config.get("name", "__PET_NAME__"))

    clock = pygame.time.Clock()
    layers = load_layers(LAYERS_DIR)

    info = pygame.display.Info()
    screen_w, screen_h = info.current_w, info.current_h
    pet_x = clamp(screen_w // 2 - w // 2, 0, max(0, screen_w - w))
    pet_y = clamp(screen_h - h - 100, 0, max(0, screen_h - h))

    start_time = time.time()
    next_blink = start_time + random.uniform(
        anim.get("blink_interval_min", 3),
        anim.get("blink_interval_max", 6))
    blink_until = 0
    next_expression = start_time + anim.get("expression_change_interval", 10)
    next_move = start_time + 10
    dragging = False
    drag_offset = (0, 0)

    current_expr = "normal"
    target_expr = "normal"
    expr_transition_start = 0
    expr_transition_time = anim.get("expression_transition_time", 0.3)

    face_layers = []
    eye_layers = []
    mouth_layers = []
    eyebrow_layers = []
    other_layers = []
    
    for name, surf in layers:
        group = get_layer_group(name, layer_groups)
        if group == "face":
            face_layers.append((name, surf, group))
        elif group == "eyes":
            eye_layers.append((name, surf, group))
        elif group == "mouth":
            mouth_layers.append((name, surf, group))
        elif group == "eyebrows":
            eyebrow_layers.append((name, surf, group))
        else:
            other_layers.append((name, surf, group))

    running = True
    while running:
        now = time.time()
        t = now - start_time
        dt = clock.tick(fps) / 1000.0

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
            elif event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 1:
                    mx, my = event.pos
                    dragging = True
                    drag_offset = (mx - pet_x, my - pet_y)
                    target_expr = "happy"
                    expr_transition_start = now
                    next_expression = now + 3
                elif event.button == 3:
                    expr_list = list(expressions.keys())
                    target_expr = random.choice([e for e in expr_list if e != current_expr])
                    expr_transition_start = now
                    next_expression = now + random.uniform(5, 12)
            elif event.type == pygame.MOUSEBUTTONUP:
                if event.button == 1:
                    dragging = False
            elif event.type == pygame.MOUSEMOTION:
                if dragging:
                    mx, my = event.pos
                    pet_x = clamp(mx - drag_offset[0], 0, max(0, screen_w - w))
                    pet_y = clamp(my - drag_offset[1], 0, max(0, screen_h - h))

        if now > next_move and not dragging:
            max_x = max(50, screen_w - w - 50)
            pet_x = random.randint(min(50, max_x), max_x)
            next_move = now + random.uniform(8, 15)

        if now > next_expression and not dragging:
            expr_list = list(expressions.keys())
            weights = {
                "normal": 4,
                "happy": 2,
                "shy": 1,
                "surprised": 1,
                "sleepy": 1,
                "angry": 0.5,
                "sad": 0.5,
            }
            weighted_list = []
            for expr in expr_list:
                weighted_list.extend([expr] * int(weights.get(expr, 1) * 2))
            target_expr = random.choice([e for e in weighted_list if e != current_expr])
            expr_transition_start = now
            next_expression = now + random.uniform(8, 15)

        transition_progress = clamp((now - expr_transition_start) / expr_transition_time, 0, 1)
        if transition_progress >= 1:
            current_expr = target_expr

        base_expr = expressions.get(current_expr, expressions.get("normal", {}))
        target_expr_data = expressions.get(target_expr, expressions.get("normal", {}))

        mouth_scale_y = lerp(base_expr.get("mouth_scale_y", 1.0), target_expr_data.get("mouth_scale_y", 1.0), transition_progress)
        mouth_scale_x = lerp(base_expr.get("mouth_scale_x", 1.0), target_expr_data.get("mouth_scale_x", 1.0), transition_progress)
        eye_open = lerp(base_expr.get("eye_open", 1.0), target_expr_data.get("eye_open", 1.0), transition_progress)
        eye_scale_x = lerp(base_expr.get("eye_scale_x", 1.0), target_expr_data.get("eye_scale_x", 1.0), transition_progress)
        eyebrow_angle = lerp(base_expr.get("eyebrow_angle", 0.0), target_expr_data.get("eyebrow_angle", 0.0), transition_progress)
        eyebrow_offset_y = lerp(base_expr.get("eyebrow_offset_y", 0.0), target_expr_data.get("eyebrow_offset_y", 0.0), transition_progress)
        blush_intensity = lerp(base_expr.get("blush_intensity", 0.0), target_expr_data.get("blush_intensity", 0.0), transition_progress)
        face_offset_y = lerp(base_expr.get("face_offset_y", 0.0), target_expr_data.get("face_offset_y", 0.0), transition_progress)
        face_offset_x = lerp(base_expr.get("face_offset_x", 0.0), target_expr_data.get("face_offset_x", 0.0), transition_progress)

        blink_eye_open = 1.0
        if now < blink_until:
            blink_progress = (blink_until - now) / anim.get("blink_duration", 0.15)
            blink_eye_open = blink_progress
        elif now > next_blink:
            blink_until = now + anim.get("blink_duration", 0.15)
            next_blink = now + random.uniform(
                anim.get("blink_interval_min", 3),
                anim.get("blink_interval_max", 6))

        final_eye_open = min(eye_open, blink_eye_open)

        screen.fill((0, 0, 0, 0))

        swing = math.sin(t * anim.get("body_swing_speed", 0.8)) * anim.get("body_swing_amplitude", 3)
        breath = math.sin(t * anim.get("breath_speed", 0.4)) * anim.get("breath_amplitude", 1.5)
        hair_swing = swing * anim.get("hair_swing_multiplier", 1.8)

        for name, surf, group in other_layers:
            offset_x, offset_y = 0, breath

            if group == "hair_front" or group == "hair_back":
                offset_x = hair_swing
            elif group == "body_swing":
                offset_x = swing * 0.5

            screen.blit(surf, (pet_x + offset_x, pet_y + offset_y))

        for name, surf, group in face_layers:
            offset_x, offset_y = swing * 0.3 + face_offset_x, breath + face_offset_y
            screen.blit(surf, (pet_x + offset_x, pet_y + offset_y))

        for name, surf, group in eyebrow_layers:
            offset_x, offset_y = swing * 0.3 + face_offset_x, breath + face_offset_y + eyebrow_offset_y
            
            sw, sh = surf.get_size()
            center_x, center_y = sw // 2, sh // 2
            
            rotated = pygame.transform.rotate(surf, math.degrees(eyebrow_angle))
            rw, rh = rotated.get_size()
            
            draw_x = pet_x + offset_x + center_x - rw // 2
            draw_y = pet_y + offset_y + center_y - rh // 2
            screen.blit(rotated, (draw_x, draw_y))

        for name, surf, group in eye_layers:
            offset_x, offset_y = swing * 0.3 + face_offset_x, breath + face_offset_y
            
            sw, sh = surf.get_size()
            new_h = max(1, int(sh * final_eye_open))
            new_w = int(sw * eye_scale_x)
            
            if new_h != sh or new_w != sw:
                draw_surf = pygame.transform.scale(surf, (new_w, new_h))
                offset_y += (sh - new_h) // 2
                offset_x += (sw - new_w) // 2
            else:
                draw_surf = surf
            
            screen.blit(draw_surf, (pet_x + offset_x, pet_y + offset_y))

        for name, surf, group in mouth_layers:
            offset_x, offset_y = swing * 0.3 + face_offset_x, breath + face_offset_y
            
            sw, sh = surf.get_size()
            new_h = int(sh * mouth_scale_y)
            new_w = int(sw * mouth_scale_x)
            
            if new_h != sh or new_w != sw:
                draw_surf = pygame.transform.scale(surf, (new_w, new_h))
                offset_y += (sh - new_h) // 2
                offset_x += (sw - new_w) // 2
            else:
                draw_surf = surf
            
            screen.blit(draw_surf, (pet_x + offset_x, pet_y + offset_y))

        if blush_intensity > 0:
            draw_blush(screen, w // 2, h // 2, blush_intensity, w, h)

        pygame.display.flip()

    pygame.quit()

if __name__ == "__main__":
    main()
